# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      SERVER_NAME: :80
      DEFAULT_URI: http://${SERVER_NAME:-localhost}:${HTTP_PORT:-80}
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
    volumes:
      - ./:/app
